modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId = "conditionalvideos"
version = "${version}"
displayName = "Conditional Videos"
logoFile="icon.png"
authors = "MateoF24"
description = '''
Client-side mod that plays configurable videos for gameplay events such as first join, deaths, kills, advancements, and dimension changes.
'''

[[dependencies.conditionalvideos]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.conditionalvideos]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.conditionalvideos]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.conditionalvideos]]
modId = "watermedia"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
